from __future__ import annotations

from pathlib import Path
from typing import Any

from .verification_plan import validate_verification_plan


def materialize_python_procedure(plan: dict[str, Any], output_path: Path) -> Path:
    """Materialize a resolved plan into a native OpenC3 COSMOS Python script."""

    _require_materializable(plan)
    lines = [
        *_provenance_lines(plan),
        "",
        "from openc3.script import *",
        "",
        *_operation_lines(plan, indent=""),
    ]
    return _write_python(output_path, lines)


def materialize_python_suite(plan: dict[str, Any], output_path: Path) -> Path:
    """Materialize the plan as an OpenC3 COSMOS Script Runner suite."""

    _require_materializable(plan)
    lines = [
        *_provenance_lines(plan),
        "",
        "from openc3.script import *",
        "from openc3.script.suite import Group, Suite",
        "",
        "",
        "class OrbitFabricVerificationGroup(Group):",
        "    def test_scenario(self):",
        "        Group.print('OrbitFabric verification projection')",
        *_operation_lines(plan, indent="        "),
        "",
        "",
        "class OrbitFabricVerificationSuite(Suite):",
        "    def __init__(self):",
        "        super().__init__()",
        "        self.add_group(OrbitFabricVerificationGroup)",
    ]
    return _write_python(output_path, lines)


def _require_materializable(plan: dict[str, Any]) -> None:
    validate_verification_plan(plan)
    if plan["status"] != "executable_subset":
        raise ValueError("blocked verification plan cannot be materialized")


def _provenance_lines(plan: dict[str, Any]) -> list[str]:
    return [
        "# Generated by orbitfabric-openc3-cosmos-adapter",
        "# Target-owned artifact; not a generic OrbitFabric Core contract.",
        f"# Scenario: {plan['source']['scenario_id']}",
        f"# Scenario SHA256: {plan['source']['scenario_sha256']}",
        f"# Core Input Set SHA256: {plan['core_input']['input_set_sha256']}",
        f"# Projection Profile: {plan['profile']['id']}@{plan['profile']['version']}",
        f"# Projection Profile SHA256: {plan['profile']['sha256']}",
        f"# COSMOS baseline: {plan['target']['baseline']}",
    ]


def _operation_lines(plan: dict[str, Any], *, indent: str) -> list[str]:
    lines: list[str] = []
    for operation in plan["operations"]:
        lines.append(
            f"{indent}# {operation['id']} <- {operation['source_atom_id']} "
            f"({operation['binding_id']})"
        )
        if operation["operation"] == "send_command":
            statement = _materialize_send_command(operation["resolved"])
        elif operation["operation"] == "wait_telemetry":
            statement = _materialize_wait_telemetry(operation["resolved"])
        else:
            raise ValueError(f"unsupported resolved COSMOS operation: {operation['operation']}")
        lines.append(f"{indent}{statement}")
        lines.append("")
    return lines


def _materialize_send_command(resolved: dict[str, Any]) -> str:
    arguments = resolved["arguments"]
    if arguments:
        raise ValueError("command argument materialization is not supported in initial scope")
    command_text = f"{resolved['target']} {resolved['command']}"
    return f"cmd({_python_string(command_text)})"


def _materialize_wait_telemetry(resolved: dict[str, Any]) -> str:
    comparison = (
        f"{resolved['target']} {resolved['packet']} {resolved['item']} "
        f"{resolved['operator']} {_cosmos_comparison_literal(resolved['expected_value'])}"
    )
    timeout = _number_literal(resolved["timeout_s"])
    if resolved.get("value_encoding", "identity") == "boolean_01":
        return f"wait_check({_python_string(comparison)}, {timeout}, type='RAW')"
    return f"wait_check({_python_string(comparison)}, {timeout})"


def _cosmos_comparison_literal(value: Any) -> str:
    if value is None:
        raise ValueError("null telemetry expectation is unsupported in initial scope")
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    raise ValueError(f"unsupported COSMOS comparison value type: {type(value).__name__}")


def _number_literal(value: int | float) -> str:
    numeric = float(value)
    if numeric.is_integer():
        return str(int(numeric))
    return repr(numeric)


def _python_string(value: str) -> str:
    return repr(value)


def _write_python(output_path: Path, lines: list[str]) -> Path:
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output_path
